package org.onvif.ver10.replay.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-18T11:13:42.355-07:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "ReplayService",
                  wsdlLocation = "file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/replay_2.2.1.wsdl",
                  targetNamespace = "http://www.onvif.org/ver10/replay/wsdl")
public class ReplayService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.onvif.org/ver10/replay/wsdl", "ReplayService");
    public final static QName ReplayPort = new QName("http://www.onvif.org/ver10/replay/wsdl", "ReplayPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/replay_2.2.1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReplayService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/replay_2.2.1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReplayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReplayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReplayService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReplayService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReplayService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReplayService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReplayPort
     */
    @WebEndpoint(name = "ReplayPort")
    public ReplayPort getReplayPort() {
        return super.getPort(ReplayPort, ReplayPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReplayPort
     */
    @WebEndpoint(name = "ReplayPort")
    public ReplayPort getReplayPort(WebServiceFeature... features) {
        return super.getPort(ReplayPort, ReplayPort.class, features);
    }

}
