package org.onvif.ver10.deviceio.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-18T11:13:05.571-07:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "DeviceIOPService",
                  wsdlLocation = "file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/deviceio_2.6.1.wsdl",
                  targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
public class DeviceIOPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.onvif.org/ver10/deviceIO/wsdl", "DeviceIOPService");
    public final static QName DeviceIOPort = new QName("http://www.onvif.org/ver10/deviceIO/wsdl", "DeviceIOPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/deviceio_2.6.1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeviceIOPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/spring/onvif/onvif-ws-client/src/main/resources/wsdl/deviceio_2.6.1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeviceIOPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceIOPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceIOPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DeviceIOPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeviceIOPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeviceIOPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DeviceIOPort
     */
    @WebEndpoint(name = "DeviceIOPort")
    public DeviceIOPort getDeviceIOPort() {
        return super.getPort(DeviceIOPort, DeviceIOPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceIOPort
     */
    @WebEndpoint(name = "DeviceIOPort")
    public DeviceIOPort getDeviceIOPort(WebServiceFeature... features) {
        return super.getPort(DeviceIOPort, DeviceIOPort.class, features);
    }

}
